package com.lintang.second.base.modular.model.match

data class SingleMatch(
    val dateEvent: String,
    val dateEventLocal: String,
    val idAwayTeam: String,
    val idEvent: String,
    val idHomeTeam: String,
    val idLeague: String,
    val idSoccerXML: String,
    val intAwayScore: String,
    val intAwayShots: String,
    val intHomeScore: String,
    val intHomeShots: String,
    val intRound: String,
    val intSpectators: String,
    val strAwayFormation: String,
    val strAwayGoalDetails: String,
    val strAwayLineupDefense: String,
    val strAwayLineupForward: String,
    val strAwayLineupGoalkeeper: String,
    val strAwayLineupMidfield: String,
    val strAwayLineupSubstitutes: String,
    val strAwayRedCards: String,
    val strAwayTeam: String,
    val strAwayYellowCards: String,
    val strBanner: String,
    val strCircuit: String,
    val strCity: String,
    val strCountry: String,
    val strDate: String,
    val strDescriptionEN: String,
    val strEvent: String,
    val strHomeFormation: String,
    val strHomeGoalDetails: String,
    val strHomeLineupDefense: String,
    val strHomeLineupForward: String,
    val strHomeLineupGoalkeeper: String,
    val strHomeLineupMidfield: String,
    val strHomeLineupSubstitutes: String,
    val strHomeRedCards: String,
    val strHomeTeam: String,
    val strHomeYellowCards: String,
    val strTime: String

)